Change syntax for checking for existence of DQ
The get_subarray method used 'if "dq" in ref:' to check whether a
reference file model has a dq array.  This no longer works:
TypeError: 'dict_items' object is not an iterator
so it has been changed to 'if hasattr(ref, "dq"):'.  See issue #1511.